// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/gvir/v1/gvir.proto

package gvirpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Package struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion    string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`          // gvir schema version; loader rejects mismatches
	GoVersion        string                 `protobuf:"bytes,2,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`                      // Go toolchain, e.g. "go1.25.5"
	ExtractorVersion string                 `protobuf:"bytes,3,opt,name=extractor_version,json=extractorVersion,proto3" json:"extractor_version,omitempty"` // extractor's own version constant
	ImportPath       string                 `protobuf:"bytes,4,opt,name=import_path,json=importPath,proto3" json:"import_path,omitempty"`
	Files            []*File                `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty"`                             // sorted by path
	Types            []*Type                `protobuf:"bytes,6,rep,name=types,proto3" json:"types,omitempty"`                             // by id; ids are first-encounter order
	Functions        []*Function            `protobuf:"bytes,7,rep,name=functions,proto3" json:"functions,omitempty"`                     // sorted by id
	MethodSets       []*MethodSet           `protobuf:"bytes,8,rep,name=method_sets,json=methodSets,proto3" json:"method_sets,omitempty"` // sorted by type id
	Pragmas          []*Pragma              `protobuf:"bytes,9,rep,name=pragmas,proto3" json:"pragmas,omitempty"`                         // sorted by (decl_id, text)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_proto_gvir_v1_gvir_proto_rawDescGZIP(), []int{0}
}

func (x *Package) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *Package) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *Package) GetExtractorVersion() string {
	if x != nil {
		return x.ExtractorVersion
	}
	return ""
}

func (x *Package) GetImportPath() string {
	if x != nil {
		return x.ImportPath
	}
	return ""
}

func (x *Package) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Package) GetTypes() []*Type {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *Package) GetFunctions() []*Function {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *Package) GetMethodSets() []*MethodSet {
	if x != nil {
		return x.MethodSets
	}
	return nil
}

func (x *Package) GetPragmas() []*Pragma {
	if x != nil {
		return x.Pragmas
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`     // module-root-relative or $GOROOT/…-prefixed; never absolute
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"` // hex digest of the source bytes; "" if unreadable
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_proto_gvir_v1_gvir_proto_rawDescGZIP(), []int{1}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    // 1-based
	Repr          string                 `protobuf:"bytes,2,opt,name=repr,proto3" json:"repr,omitempty"` // types.TypeString with full-package-path qualifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_proto_gvir_v1_gvir_proto_rawDescGZIP(), []int{2}
}

func (x *Type) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Type) GetRepr() string {
	if x != nil {
		return x.Repr
	}
	return ""
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          uint32                 `protobuf:"varint,1,opt,name=file,proto3" json:"file,omitempty"` // 1-based index into Package.files; 0 = unknown file
	Line          uint32                 `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Col           uint32                 `protobuf:"varint,3,opt,name=col,proto3" json:"col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_proto_gvir_v1_gvir_proto_rawDescGZIP(), []int{3}
}

func (x *Position) GetFile() uint32 {
	if x != nil {
		return x.File
	}
	return 0
}

func (x *Position) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Position) GetCol() uint32 {
	if x != nil {
		return x.Col
	}
	return 0
}

// Function value numbering: ids are assigned 1,2,3,… in this order:
// params (declaration order), free vars, then every value-producing
// instruction walking blocks by index; any operand not yet numbered
// (const/global/function/builtin) is assigned the next id as an
// AuxValue at first encounter. The walk is deterministic, so ids are.
type Function struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ssa.Function.String(), e.g. "(*example.com/m.T).Close"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          uint32                 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`    // signature type id
	Params        []*Param               `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty"` // declaration order
	Aux           []*AuxValue            `protobuf:"bytes,5,rep,name=aux,proto3" json:"aux,omitempty"`       // ascending id
	Blocks        []*BasicBlock          `protobuf:"bytes,6,rep,name=blocks,proto3" json:"blocks,omitempty"` // by block index; empty for bodyless funcs
	Pos           *Position              `protobuf:"bytes,7,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_proto_gvir_v1_gvir_proto_rawDescGZIP(), []int{4}
}

func (x *Function) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Function) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Function) GetParams() []*Param {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Function) GetAux() []*AuxValue {
	if x != nil {
		return x.Aux
	}
	return nil
}

func (x *Function) GetBlocks() []*BasicBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *Function) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

type Param struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          uint32                 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Param) Reset() {
	*x = Param{}
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_proto_gvir_v1_gvir_proto_rawDescGZIP(), []int{5}
}

func (x *Param) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Param) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Param) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// Non-instruction values an instruction can reference.
type AuxValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // "Const" | "Global" | "Function" | "Builtin" | "FreeVar" | "Value"
	Repr          string                 `protobuf:"bytes,3,opt,name=repr,proto3" json:"repr,omitempty"` // the value's canonical ssa String()
	Type          uint32                 `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuxValue) Reset() {
	*x = AuxValue{}
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuxValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuxValue) ProtoMessage() {}

func (x *AuxValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuxValue.ProtoReflect.Descriptor instead.
func (*AuxValue) Descriptor() ([]byte, []int) {
	return file_proto_gvir_v1_gvir_proto_rawDescGZIP(), []int{6}
}

func (x *AuxValue) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuxValue) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AuxValue) GetRepr() string {
	if x != nil {
		return x.Repr
	}
	return ""
}

func (x *AuxValue) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type BasicBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Instrs        []*Instruction         `protobuf:"bytes,2,rep,name=instrs,proto3" json:"instrs,omitempty"`       // program order
	Succs         []uint32               `protobuf:"varint,3,rep,packed,name=succs,proto3" json:"succs,omitempty"` // successor block indexes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicBlock) Reset() {
	*x = BasicBlock{}
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicBlock) ProtoMessage() {}

func (x *BasicBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicBlock.ProtoReflect.Descriptor instead.
func (*BasicBlock) Descriptor() ([]byte, []int) {
	return file_proto_gvir_v1_gvir_proto_rawDescGZIP(), []int{7}
}

func (x *BasicBlock) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BasicBlock) GetInstrs() []*Instruction {
	if x != nil {
		return x.Instrs
	}
	return nil
}

func (x *BasicBlock) GetSuccs() []uint32 {
	if x != nil {
		return x.Succs
	}
	return nil
}

type Instruction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`                 // ssa type name: "Call", "Store", "Phi", …
	Register      uint32                 `protobuf:"varint,2,opt,name=register,proto3" json:"register,omitempty"`        // value id this instruction defines; 0 if none
	Type          uint32                 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`                // result type id; 0 if none
	Operands      []uint32               `protobuf:"varint,4,rep,packed,name=operands,proto3" json:"operands,omitempty"` // value ids; 0 for nil operand slots
	Pos           *Position              `protobuf:"bytes,5,opt,name=pos,proto3" json:"pos,omitempty"`
	Detail        string                 `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"` // the instruction's canonical ssa String()
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instruction) Reset() {
	*x = Instruction{}
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instruction) ProtoMessage() {}

func (x *Instruction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instruction.ProtoReflect.Descriptor instead.
func (*Instruction) Descriptor() ([]byte, []int) {
	return file_proto_gvir_v1_gvir_proto_rawDescGZIP(), []int{8}
}

func (x *Instruction) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Instruction) GetRegister() uint32 {
	if x != nil {
		return x.Register
	}
	return 0
}

func (x *Instruction) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Instruction) GetOperands() []uint32 {
	if x != nil {
		return x.Operands
	}
	return nil
}

func (x *Instruction) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Instruction) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type MethodSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`      // type id of the named type T
	Methods       []string               `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"` // fully-qualified method names of *T's method set (T itself if T is an interface), in types.NewMethodSet order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodSet) Reset() {
	*x = MethodSet{}
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodSet) ProtoMessage() {}

func (x *MethodSet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodSet.ProtoReflect.Descriptor instead.
func (*MethodSet) Descriptor() ([]byte, []int) {
	return file_proto_gvir_v1_gvir_proto_rawDescGZIP(), []int{9}
}

func (x *MethodSet) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MethodSet) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type Pragma struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeclId        string                 `protobuf:"bytes,1,opt,name=decl_id,json=declId,proto3" json:"decl_id,omitempty"` // types.Func.FullName() or "pkgpath.Name" of the decl
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                   // full comment line including "//goverify:"
	Pos           *Position              `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pragma) Reset() {
	*x = Pragma{}
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pragma) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pragma) ProtoMessage() {}

func (x *Pragma) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gvir_v1_gvir_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pragma.ProtoReflect.Descriptor instead.
func (*Pragma) Descriptor() ([]byte, []int) {
	return file_proto_gvir_v1_gvir_proto_rawDescGZIP(), []int{10}
}

func (x *Pragma) GetDeclId() string {
	if x != nil {
		return x.DeclId
	}
	return ""
}

func (x *Pragma) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Pragma) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

var File_proto_gvir_v1_gvir_proto protoreflect.FileDescriptor

const file_proto_gvir_v1_gvir_proto_rawDesc = "" +
	"\n" +
	"\x18proto/gvir/v1/gvir.proto\x12\agvir.v1\"\xf8\x02\n" +
	"\aPackage\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x1d\n" +
	"\n" +
	"go_version\x18\x02 \x01(\tR\tgoVersion\x12+\n" +
	"\x11extractor_version\x18\x03 \x01(\tR\x10extractorVersion\x12\x1f\n" +
	"\vimport_path\x18\x04 \x01(\tR\n" +
	"importPath\x12#\n" +
	"\x05files\x18\x05 \x03(\v2\r.gvir.v1.FileR\x05files\x12#\n" +
	"\x05types\x18\x06 \x03(\v2\r.gvir.v1.TypeR\x05types\x12/\n" +
	"\tfunctions\x18\a \x03(\v2\x11.gvir.v1.FunctionR\tfunctions\x123\n" +
	"\vmethod_sets\x18\b \x03(\v2\x12.gvir.v1.MethodSetR\n" +
	"methodSets\x12)\n" +
	"\apragmas\x18\t \x03(\v2\x0f.gvir.v1.PragmaR\apragmas\"2\n" +
	"\x04File\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"*\n" +
	"\x04Type\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04repr\x18\x02 \x01(\tR\x04repr\"D\n" +
	"\bPosition\x12\x12\n" +
	"\x04file\x18\x01 \x01(\rR\x04file\x12\x12\n" +
	"\x04line\x18\x02 \x01(\rR\x04line\x12\x10\n" +
	"\x03col\x18\x03 \x01(\rR\x03col\"\xe1\x01\n" +
	"\bFunction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\rR\x04type\x12&\n" +
	"\x06params\x18\x04 \x03(\v2\x0e.gvir.v1.ParamR\x06params\x12#\n" +
	"\x03aux\x18\x05 \x03(\v2\x11.gvir.v1.AuxValueR\x03aux\x12+\n" +
	"\x06blocks\x18\x06 \x03(\v2\x13.gvir.v1.BasicBlockR\x06blocks\x12#\n" +
	"\x03pos\x18\a \x01(\v2\x11.gvir.v1.PositionR\x03pos\"?\n" +
	"\x05Param\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\rR\x04type\"V\n" +
	"\bAuxValue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04repr\x18\x03 \x01(\tR\x04repr\x12\x12\n" +
	"\x04type\x18\x04 \x01(\rR\x04type\"f\n" +
	"\n" +
	"BasicBlock\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12,\n" +
	"\x06instrs\x18\x02 \x03(\v2\x14.gvir.v1.InstructionR\x06instrs\x12\x14\n" +
	"\x05succs\x18\x03 \x03(\rR\x05succs\"\xaa\x01\n" +
	"\vInstruction\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1a\n" +
	"\bregister\x18\x02 \x01(\rR\bregister\x12\x12\n" +
	"\x04type\x18\x03 \x01(\rR\x04type\x12\x1a\n" +
	"\boperands\x18\x04 \x03(\rR\boperands\x12#\n" +
	"\x03pos\x18\x05 \x01(\v2\x11.gvir.v1.PositionR\x03pos\x12\x16\n" +
	"\x06detail\x18\x06 \x01(\tR\x06detail\"9\n" +
	"\tMethodSet\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x18\n" +
	"\amethods\x18\x02 \x03(\tR\amethods\"Z\n" +
	"\x06Pragma\x12\x17\n" +
	"\adecl_id\x18\x01 \x01(\tR\x06declId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12#\n" +
	"\x03pos\x18\x03 \x01(\v2\x11.gvir.v1.PositionR\x03posB\x1fZ\x1dgoverify.dev/extractor/gvirpbb\x06proto3"

var (
	file_proto_gvir_v1_gvir_proto_rawDescOnce sync.Once
	file_proto_gvir_v1_gvir_proto_rawDescData []byte
)

func file_proto_gvir_v1_gvir_proto_rawDescGZIP() []byte {
	file_proto_gvir_v1_gvir_proto_rawDescOnce.Do(func() {
		file_proto_gvir_v1_gvir_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gvir_v1_gvir_proto_rawDesc), len(file_proto_gvir_v1_gvir_proto_rawDesc)))
	})
	return file_proto_gvir_v1_gvir_proto_rawDescData
}

var file_proto_gvir_v1_gvir_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_gvir_v1_gvir_proto_goTypes = []any{
	(*Package)(nil),     // 0: gvir.v1.Package
	(*File)(nil),        // 1: gvir.v1.File
	(*Type)(nil),        // 2: gvir.v1.Type
	(*Position)(nil),    // 3: gvir.v1.Position
	(*Function)(nil),    // 4: gvir.v1.Function
	(*Param)(nil),       // 5: gvir.v1.Param
	(*AuxValue)(nil),    // 6: gvir.v1.AuxValue
	(*BasicBlock)(nil),  // 7: gvir.v1.BasicBlock
	(*Instruction)(nil), // 8: gvir.v1.Instruction
	(*MethodSet)(nil),   // 9: gvir.v1.MethodSet
	(*Pragma)(nil),      // 10: gvir.v1.Pragma
}
var file_proto_gvir_v1_gvir_proto_depIdxs = []int32{
	1,  // 0: gvir.v1.Package.files:type_name -> gvir.v1.File
	2,  // 1: gvir.v1.Package.types:type_name -> gvir.v1.Type
	4,  // 2: gvir.v1.Package.functions:type_name -> gvir.v1.Function
	9,  // 3: gvir.v1.Package.method_sets:type_name -> gvir.v1.MethodSet
	10, // 4: gvir.v1.Package.pragmas:type_name -> gvir.v1.Pragma
	5,  // 5: gvir.v1.Function.params:type_name -> gvir.v1.Param
	6,  // 6: gvir.v1.Function.aux:type_name -> gvir.v1.AuxValue
	7,  // 7: gvir.v1.Function.blocks:type_name -> gvir.v1.BasicBlock
	3,  // 8: gvir.v1.Function.pos:type_name -> gvir.v1.Position
	8,  // 9: gvir.v1.BasicBlock.instrs:type_name -> gvir.v1.Instruction
	3,  // 10: gvir.v1.Instruction.pos:type_name -> gvir.v1.Position
	3,  // 11: gvir.v1.Pragma.pos:type_name -> gvir.v1.Position
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_gvir_v1_gvir_proto_init() }
func file_proto_gvir_v1_gvir_proto_init() {
	if File_proto_gvir_v1_gvir_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gvir_v1_gvir_proto_rawDesc), len(file_proto_gvir_v1_gvir_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_gvir_v1_gvir_proto_goTypes,
		DependencyIndexes: file_proto_gvir_v1_gvir_proto_depIdxs,
		MessageInfos:      file_proto_gvir_v1_gvir_proto_msgTypes,
	}.Build()
	File_proto_gvir_v1_gvir_proto = out.File
	file_proto_gvir_v1_gvir_proto_goTypes = nil
	file_proto_gvir_v1_gvir_proto_depIdxs = nil
}
